version: '3'


services:
  db_ver_mongo:
    container_name: db_ver_mongo
    image: mongo
    ports:
      - 27020:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: ver
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  mongoweb:
    container_name: mongo_web_ver
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: db_ver_mongo
      # ME_CONFIG_MONGODB_PORT: 27019
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - 8085:8081
    depends_on:
      - db_ver_mongo